global using BuildingBlocks.SQRS;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Ordering.Application.Data;
global using Ordering.Application.Dtos;
global using Ordering.Application.Exceptions;
global using Ordering.Domain.Events;
global using Ordering.Domain.Models;
global using Ordering.Domain.Models.ValueObjects;
